apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: api-gateway-ingress
  namespace: ingress-controller
spec:
  #ingressClassName: nginx
  rules:
  - host: gateway.richardktran.local
    http:
      paths:
      - backend:
          service:
            name: "api-gateway"
            port:
              number: 80
            namespace: development
        path: /
        pathType: Prefix