apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: development
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gateway.richardktran.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80