apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: ingress-controller
spec:
  rules:
  - host: gateway.richardktran.local
    http:
      paths:
      - path: /
        backend:
          serviceName: api-gateway
          servicePort: 80