apiVersion: v1
kind: Service
metadata:
  labels:
    app: "api-gateway"
  name: "api-gateway"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: "api-gateway"
  sessionAffinity: None
  type: NodePort
